### ISSUE TITLE
Invalid string escape \v allowed in strings

### ISSUE THREAD

**Issue by eugenesvk** [tjol/ckdl#11]
Using the pypi version `"\v"` should be invalid since you can only escape `\"bfnrts`

```py
    kdl_txt = """
      /-n "arg\v";
    """
    try:
      doc = ckdl.parse(kdl_txt)
      print(doc)
```

**Comment by tjol** [comment]
Thanks for the report.

The string you're testing does _not_ contain the sequence `\v`. **Python** recognizes this escape sequence and turns it into a vertical tab (`"\x0b"` in Python, `"\u{b}"` in KDL):

```
>>> kdl_txt = """
...     /-n "arg\v";
... """
>>> kdl_txt
'\n    /-n "arg\x0b";\n'
>>> 
```

A string containing a vertical tab character is legal in KDL v1 (and erroneously treated as legal in v2 by ckdl, but that's another matter #12)

If you pass a string with backslash `\` followed by `v` to ckdl (e.g. `r'''/-n "arg\v";'''` or `'/-n "arg\\v";'`), this will throw an exception as expected.

See Python's escape sequences: https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences
